<?php

/**
 * @file
 * Contains user_phone.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function user_phone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_phone module.
    case 'help.page.user_phone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_phone_theme() {
  return [
    'user_phone' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_install().
 */
function user_phone_install()
{
    $permissions = [
        'restful post user_phone_bind_phone'
    ];
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions);
}

/**
 * Implements hook_entity_base_field_info().
 */
function user_phone_entity_base_field_info(EntityTypeInterface $entity_type) {
    $fields = [];
    if ($entity_type->id() == 'user') {

        $fields['phone'] = BaseFieldDefinition::create('string')
            ->setLabel(t('Phone number'))
            ->setDisplayOptions('view', [
                'label' => 'inline',
                'type' => 'string'
            ])
            ->setDisplayOptions('form', [
                'type' => 'string_textfield'
            ])
            ->setDisplayConfigurable('view', true)
            ->setDisplayConfigurable('form', true);
    }
    return $fields;
}
